//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaEvaluation.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IdeaEvaluationEntities : DbContext
    {
        public IdeaEvaluationEntities()
            : base("name=IdeaEvaluationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<evaluation> evaluations { get; set; }
        public virtual DbSet<idea> ideas { get; set; }
        public virtual DbSet<judge> judges { get; set; }
    
        public virtual ObjectResult<IdeaAssignment_Result> IdeaAssignment(Nullable<int> judgeId, Nullable<int> ideasPerJudge, Nullable<int> minTimesIdeaEvaluates)
        {
            var judgeIdParameter = judgeId.HasValue ?
                new ObjectParameter("JudgeId", judgeId) :
                new ObjectParameter("JudgeId", typeof(int));
    
            var ideasPerJudgeParameter = ideasPerJudge.HasValue ?
                new ObjectParameter("IdeasPerJudge", ideasPerJudge) :
                new ObjectParameter("IdeasPerJudge", typeof(int));
    
            var minTimesIdeaEvaluatesParameter = minTimesIdeaEvaluates.HasValue ?
                new ObjectParameter("MinTimesIdeaEvaluates", minTimesIdeaEvaluates) :
                new ObjectParameter("MinTimesIdeaEvaluates", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IdeaAssignment_Result>("IdeaAssignment", judgeIdParameter, ideasPerJudgeParameter, minTimesIdeaEvaluatesParameter);
        }
    }
}
